# Generated by Django 4.2.7 on 2025-10-01 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('data_acesso', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'acessos',
                'ordering': ['-data_acesso'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('total_acessos', models.IntegerField(default=0)),
                ('primeiro_acesso', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_acesso', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'estatisticas_usuario',
            },
        ),
    ]
